name: pathocore
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10.17
  - biopython=1.85
  - numpy=2.2.5
  - pandas=2.2.3
  - pip=25.0.1
  - scikit-learn=1.6.1
  - pip:
      - matplotlib==3.10.1
      - seaborn==0.13.2
      - tqdm==4.67.1
